"""Encode the PNG frames as a Lua module of coloured cell runs.

chafa picks the half-block glyphs and colours; this parses its output back into
cells. Colours are quantised because every distinct fg/bg pair costs a highlight
group and the raw frames use ~20k of them.
"""

import os
import re
import subprocess
import sys

SRC, OUT = sys.argv[1], sys.argv[2]
CHAFA = os.environ.get("CHAFA", "chafa")
COLS, ROWS = int(os.environ.get("COLS", "60")), int(os.environ.get("ROWS", "20"))
FPS = int(os.environ.get("FPS", "16"))
QUANT = int(os.environ.get("QUANT", "16"))

SGR = re.compile(rb"\x1b\[([0-9;]*)m")
ESC = re.compile(rb"\x1b\[[0-9;?]*[A-Za-z]")


def quant(c):
    if c is None:
        return None
    return tuple(min(255, (v + QUANT // 2) // QUANT * QUANT) for v in c)


def cells(ansi):
    """chafa output -> ROWS lists of (char, fg, bg), colours quantised."""
    grid = [[] for _ in range(ROWS)]
    row, fg, bg = 0, None, None
    i = 0
    while i < len(ansi) and row < ROWS:
        m = SGR.match(ansi, i)
        if m:
            params = m.group(1)
            p = [int(x) if x else 0 for x in params.split(b";")] if params else [0]
            j = 0
            while j < len(p):
                if p[j] == 0:
                    fg = bg = None
                    j += 1
                elif p[j] == 38 and p[j + 1 : j + 2] == [2]:
                    fg = quant(tuple(p[j + 2 : j + 5]))
                    j += 5
                elif p[j] == 48 and p[j + 1 : j + 2] == [2]:
                    bg = quant(tuple(p[j + 2 : j + 5]))
                    j += 5
                else:
                    j += 1
            i = m.end()
            continue
        m = ESC.match(ansi, i)
        if m:  # cursor show/hide and friends carry no cells
            i = m.end()
            continue
        ch = ansi[i : i + 1]
        if ch == b"\n":
            row += 1
        elif ch != b"\r":
            char = ansi[i:].decode("utf-8", "replace")[0]
            if row < ROWS:
                grid[row].append((char, fg, bg))
            i += len(char.encode("utf-8"))
            continue
        i += 1
    return grid


def runs(row, pal):
    """Merge neighbouring cells sharing a colour pair into one chunk."""
    out = []
    for char, fg, bg in row:
        key = (fg, bg)
        idx = 0
        if fg is not None or bg is not None:
            if key not in pal:
                pal[key] = len(pal) + 1
            idx = pal[key]
        if out and out[-1][1] == idx:
            out[-1][0] += char
        else:
            out.append([char, idx])
    return out


def lua(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


palette, frames = {}, []
names = sorted(f for f in os.listdir(SRC) if f.endswith(".png"))
size = f"{COLS}x{ROWS}"
for name in names:
    ansi = subprocess.run(
        [
            CHAFA, os.path.join(SRC, name),
            "--format", "symbols", "--symbols", "vhalf",
            # Piped, chafa centres inside an assumed 80x25 view unless told otherwise.
            "--view-size", size, "--size", size,
            "--align", "mid,mid", "--probe", "off", "-c", "full",
        ],
        capture_output=True,
        check=True,
    ).stdout
    frames.append([runs(row, palette) for row in cells(ansi)])

os.makedirs(OUT, exist_ok=True)
with open(os.path.join(OUT, "frames.lua"), "w") as fh:
    fh.write("-- Generated by luaify.py. Cell runs per row, indexing `palette`.\n")
    fh.write(f"return {{\ncols={COLS},rows={ROWS},fps={FPS},\npalette={{\n")
    for (fg, bg), _ in sorted(palette.items(), key=lambda kv: kv[1]):
        f = '"#%02x%02x%02x"' % fg if fg else "false"
        b = '"#%02x%02x%02x"' % bg if bg else "false"
        fh.write(f"{{{f},{b}}},\n")
    fh.write("},\nframes={\n")
    for frame in frames:
        fh.write("{")
        for row in frame:
            fh.write("{" + ",".join(f"{{{lua(t)},{i}}}" for t, i in row) + "},")
        fh.write("},\n")
    fh.write("},\n}\n")

print(f"encoded {len(frames)} frames, {len(palette)} colour pairs -> {OUT}/frames.lua")
