# codeq: one entry point for code-quality metrics. Language-neutral commands run
# on any repo; JVM/Go commands detect the project and say plainly when they don't
# apply. Every command prints to stdout and keeps a copy under $CODEQ_OUT.
# CODEQ_LIB is prepended by default.nix.

OUT="${CODEQ_OUT:-$PWD/.codeq}"
INCLUDE_TESTS="${CODEQ_TESTS:-0}"

usage() {
  cat <<EOF
usage: codeq [-o DIR] [--tests] COMMAND [ARGS]

Any language
  loc                 lines of code, comments, blanks per language           tokei
  complexity [CCN]    cyclomatic complexity per function; warns above CCN    lizard
                      (default 10). Lower is easier to test and change.
  dup [TOKENS]        copy-pasted blocks of >= TOKENS tokens (default 75)    pmd cpd
  cycles              call and import cycles                                 sqry
  overview            hubs, hotspots, unused public API, fan-out             sqry

JVM (Java/Kotlin, Gradle or Maven; needs compiled classes)
  coupling [PREFIX]   Martin package metrics + graph (.codeq/coupling/):     jdeps
                        Ca  classes outside that depend on the package
                        Ce  outside classes the package depends on
                        I   Ce/(Ca+Ce): 0 stable, 1 free to change
                        A   share of abstract types
                        D   |A+I-1|: distance from the healthy balance
  design              PMD design rules + CK class metrics:                   pmd, ck
                        CBO coupling, WMC complexity, LCOM* lack of cohesion
  bugs                bug patterns in bytecode                               spotbugs

JVM or Go
  coverage [--no-run] line/branch/method coverage; runs the tests first      jacoco, go
                      unless --no-run

  all                 every command that applies here -> \$OUT/REPORT.md

Options
  -o DIR    output directory (default ./.codeq, globally gitignored)
  --tests   include test sources in loc/complexity/dup/design (default: production only)

Applies in $(pwd):
$(applicability)
EOF
}

die() {
  echo "codeq: $*" >&2
  exit 1
}

# Reads the whole list: an early-exiting grep -q would SIGPIPE the producer under pipefail.
has_files() {
  [ -n "$(source_files "$@")" ]
}

applicability() {
  local jvm="no" go="no"
  has_files java kt && jvm="yes"
  [ -f go.mod ] && go="yes"
  echo "  any-language commands  yes"
  echo "  JVM commands           $jvm"
  echo "  Go coverage            $go"
}

# Tracked + untracked-but-not-ignored files with the given extensions, minus
# build output, vendored and generated code, and (unless --tests) test sources.
source_files() {
  local exts files generated
  exts=$(printf '%s|' "$@")
  exts="${exts%|}"
  files=$(
    {
      if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        git ls-files --cached --others --exclude-standard
      else
        find . -type f -not -path './.git/*' | sed 's|^\./||'
      fi
    } |
      grep -E "\.($exts)\$" |
      grep -Ev '(^|/)(build|target|dist|out|node_modules|vendor|gen|generated|__generated__|\.codeq)/' |
      if [ "$INCLUDE_TESTS" = 1 ]; then
        cat
      else
        grep -Ev '(^|/)(test|tests|__tests__|integrationTest|testFixtures|spec)/|_test\.(go|py)$|(^|/)test_[^/]*\.py$|\.(test|spec)\.[cm]?[jt]sx?$|(Test|Tests|IT)\.(java|kt)$'
      fi |
      # git ls-files still lists tracked files deleted from the working tree.
      while IFS= read -r f; do [ -f "$f" ] && printf '%s\n' "$f"; done
  ) || true
  [ -n "$files" ] || return 0
  # Generators stamp a marker near the top; a license header can push it past line 10.
  generated=$(printf '%s\n' "$files" | xargs -d '\n' gawk '
    FNR > 20 { nextfile }
    /@generated|DO NOT EDIT|[Aa]uto-?generated|[Cc]ode generated by/ { print FILENAME; nextfile }')
  if [ -n "$generated" ]; then
    grep -vxF -f <(printf '%s\n' "$generated") <<<"$files" || true
  else
    printf '%s\n' "$files"
  fi
}

# Packages declared in hand-written JVM sources. Generated code (protobuf,
# OpenAPI) compiles into the same classes dir and would otherwise dominate.
source_packages() {
  source_files java kt | xargs -r sed -n 's/^package[[:space:]]\{1,\}\([A-Za-z0-9_.]*\).*/\1/p' | sort -u
}

jvm_classes_dirs() {
  find . \( -path '*/node_modules' -o -path './.git' \) -prune -o -type d \
    \( -path '*/build/classes/java/main' -o -path '*/build/classes/kotlin/main' -o -path '*/target/classes' \) -print
}

require_jvm() {
  has_files java kt || die "no Java/Kotlin sources here; '$1' is JVM-only"
  [ -n "$(jvm_classes_dirs)" ] || die "no compiled classes found; run 'gradle classes' or 'mvn compile' first"
}

gradle_cmd() {
  if [ -x ./gradlew ]; then echo ./gradlew; else echo gradle; fi
}

save() {
  mkdir -p "$OUT"
  tee "$OUT/$1.txt"
}

cmd_loc() {
  tokei --sort code "${@:-.}" | save loc
}

cmd_complexity() {
  local ccn="${1:-10}" list
  list=$(mktemp)
  # lizard ignores extensions it can't parse, so every source file is a candidate.
  source_files java kt go py ts tsx js jsx mjs rs c h cc cpp hpp cs swift scala rb php lua dart m >"$list"
  [ -s "$list" ] || die "no source files lizard understands"
  # lizard's exit code counts warnings; -i lifts that so only real errors fail.
  lizard -C "$ccn" -i 999999 -f "$list" >"$list.out"
  {
    sed -n '/^Total nloc/,$p' "$list.out"
    echo
    sed -n '/^!!!! Warnings/,/^Total nloc/p' "$list.out" | sed '$d' | sed '$d'
  } | save complexity
  rm -f "$list.out"
  rm -f "$list"
}

# CPD language id for each extension group it supports.
cpd_languages() {
  has_files java && echo "java java"
  has_files kt && echo "kotlin kt"
  has_files go && echo "go go"
  has_files py && echo "python py"
  has_files ts tsx && echo "typescript ts|tsx"
  # CPD's JavaScript lexer only accepts .js/.jsx; .mjs/.cjs would leave it no input.
  has_files js jsx && echo "ecmascript js|jsx"
  has_files rs && echo "rust rs"
  has_files cs && echo "cs cs"
  has_files cpp cc hpp h c && echo "cpp cpp|cc|hpp|h|c"
  has_files scala && echo "scala scala"
  has_files rb && echo "ruby rb"
  has_files swift && echo "swift swift"
  has_files php && echo "php php"
}

cmd_dup() {
  local tokens="${1:-75}" lang exts list found=0
  mkdir -p "$OUT"
  {
    while read -r lang exts; do
      found=1
      list=$(mktemp)
      # shellcheck disable=SC2086
      source_files ${exts//|/ } >"$list"
      echo "== $lang (>= $tokens tokens)"
      if [ ! -s "$list" ]; then
        rm -f "$list"
        continue
      fi
      pmd cpd --minimum-tokens "$tokens" --language "$lang" --file-list "$list" \
        --format text --no-fail-on-violation 2>>"$OUT/dup.err" | sed "s|$PWD/||"
      echo
      rm -f "$list"
    done < <(cpd_languages)
    [ "$found" = 1 ] || echo "no languages CPD supports were found"
  } | save dup
}

require_sqry() {
  command -v sqry >/dev/null || die "sqry is not available on this platform"
}

cmd_cycles() {
  require_sqry
  {
    echo "== call cycles"
    sqry cycles --type calls .
    echo
    echo "== import cycles"
    sqry cycles --type imports .
  } | save cycles
}

cmd_overview() {
  require_sqry
  sqry overview . | save overview
}

cmd_coupling() {
  require_jvm coupling
  local dir="$OUT/coupling" dirs
  mkdir -p "$dir"
  mapfile -t dirs < <(jvm_classes_dirs)
  jdeps -verbose:class -filter:none "${dirs[@]}" 2>"$dir/jdeps.err" | { grep -- '->' || true; } |
    { grep -v 'not found' || true; } >"$dir/deps.txt"
  [ -s "$dir/deps.txt" ] || die "jdeps found no dependencies in ${dirs[*]}; see $dir/jdeps.err"
  find "${dirs[@]}" -name '*.class' ! -name '*$*' -printf '%P\n' | sed 's|\.class$||; s|/|.|g' |
    xargs javap -cp "$(
      IFS=:
      echo "${dirs[*]}"
    )" 2>"$dir/javap.err" | { grep -E '(class|interface|enum|record) ' || true; } >"$dir/decls.txt"
  source_packages >"$dir/packages.txt"
  python3 "$CODEQ_LIB/martin.py" "$dir/deps.txt" "$dir/decls.txt" "$dir" \
    --packages "$dir/packages.txt" ${1:+--prefix "$1."} | save coupling
  dot -Tsvg "$dir/packages.dot" -o "$dir/packages.svg"
  echo "graph: $dir/packages.svg"
}

cmd_design() {
  require_jvm design
  local list roots
  list=$(mktemp)
  source_files java >"$list"
  [ -s "$list" ] || die "design rules need Java sources"
  rm -rf "$OUT/ck"
  mkdir -p "$OUT/ck"
  # CK takes directories; fall back to the repo root for non-Maven layouts.
  mapfile -t roots < <(sed -nE 's|^(.*src/[^/]+/java)/.*|\1|p' "$list" | sort -u)
  [ "${#roots[@]}" -gt 0 ] || roots=(.)
  {
    echo "== PMD design rules"
    pmd check -R "$CODEQ_LIB/pmd-design.xml" --file-list "$list" -f text \
      --no-progress --no-fail-on-violation 2>"$OUT/design.err" | sed "s|$PWD/||"
    echo
    echo "== CK class metrics"
    for root in "${roots[@]}"; do
      ck "$root" false 0 false "$OUT/ck/$(echo "$root" | tr / _)-" >>"$OUT/ck/ck.log" 2>&1 ||
        die "CK failed on $root; see $OUT/ck/ck.log"
    done
    python3 - "$OUT/ck" <<'PY'
import csv, glob, os, sys
out = sys.argv[1]
for kind in ("class", "method"):
    files = sorted(glob.glob(os.path.join(out, f"*-{kind}.csv")))
    rows = [r for f in files for r in csv.DictReader(open(f))]
    if rows:
        with open(os.path.join(out, f"{kind}.csv"), "w", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=rows[0].keys())
            w.writeheader()
            w.writerows(rows)
PY
    python3 "$CODEQ_LIB/ck_summary.py" "$OUT/ck"
  } | save design
  rm -f "$list"
}

jvm_aux_classpath() {
  if [ -f build.gradle ] || [ -f build.gradle.kts ] || [ -f settings.gradle ] || [ -f settings.gradle.kts ]; then
    "$(gradle_cmd)" -q --no-configuration-cache --init-script "$CODEQ_LIB/classpath.init.gradle" codeqPrintClasspath 2>"$OUT/classpath.err" |
      sed -n 's/^CODEQ_CP://p' | sort -u
  elif [ -f pom.xml ]; then
    local cp
    cp=$(mktemp)
    mvn -q dependency:build-classpath -Dmdep.outputFile="$cp" >/dev/null 2>&1 && tr ':' '\n' <"$cp"
    rm -f "$cp"
  fi
}

cmd_bugs() {
  require_jvm bugs
  local aux dirs
  aux=$(mktemp)
  mapfile -t dirs < <(jvm_classes_dirs)
  mkdir -p "$OUT"
  # Optional: without it SpotBugs still runs, just with weaker type information.
  jvm_aux_classpath >"$aux" || true
  [ -s "$aux" ] || echo "codeq: no build classpath (see $OUT/classpath.err); SpotBugs will report missing classes" >&2
  mkdir -p "$OUT"
  local only
  only=$(source_packages | sed 's/$/.*/' | paste -sd,)
  spotbugs -textui -effort:max -low -onlyAnalyze "$only" -auxclasspathFromFile "$aux" "${dirs[@]}" \
    >"$OUT/spotbugs.raw" 2>"$OUT/bugs.err" || die "spotbugs failed; see $OUT/bugs.err"
  {
    grep -E '^[HML] ' "$OUT/spotbugs.raw" | sort || echo "no findings"
    echo
    echo "priority: H high, M medium, L low; category: B bad practice, C correctness,"
    echo "V malicious code (exposed internals), I internationalisation, P performance, S security"
  } | save bugs
  rm -f "$aux"
}

cmd_coverage() {
  local run=1 reports
  [ "${1:-}" = "--no-run" ] && run=0
  if [ -f go.mod ]; then
    mkdir -p "$OUT"
    if [ "$run" = 1 ]; then
      go test ./... -coverprofile="$OUT/go-cover.out" >"$OUT/go-test.log" 2>&1 ||
        die "go test failed; see $OUT/go-test.log"
    fi
    [ -f "$OUT/go-cover.out" ] || die "no Go coverage profile; run without --no-run"
    go tool cover -func="$OUT/go-cover.out" | save coverage
    return
  fi
  has_files java kt || die "coverage supports JVM (JaCoCo) and Go projects"
  if [ "$run" = 1 ]; then
    mkdir -p "$OUT"
    if [ -f build.gradle ] || [ -f build.gradle.kts ]; then
      "$(gradle_cmd)" test jacocoTestReport >"$OUT/gradle.log" 2>&1 ||
        die "gradle test jacocoTestReport failed; see $OUT/gradle.log (is the jacoco plugin applied?)"
    elif [ -f pom.xml ]; then
      mvn -q test org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report ||
        die "maven test + jacoco report failed"
    fi
  fi
  mapfile -t reports < <(find . -path '*/node_modules' -prune -o \
    \( -path '*/build/reports/jacoco/*.xml' -o -path '*/target/site/jacoco/jacoco.xml' \) -print)
  [ "${#reports[@]}" -gt 0 ] || die "no JaCoCo XML report found (build/reports/jacoco or target/site/jacoco)"
  python3 "$CODEQ_LIB/coverage.py" "${reports[@]}" | save coverage
}

cmd_all() {
  local cmds=(loc complexity dup) failed=()
  command -v sqry >/dev/null && cmds+=(cycles overview)
  if has_files java kt && [ -n "$(jvm_classes_dirs)" ]; then
    cmds+=(coupling design bugs coverage)
  elif [ -f go.mod ]; then
    cmds+=(coverage)
  fi
  mkdir -p "$OUT"
  {
    echo "# codeq report: $(basename "$PWD") ($(date -I))"
    for c in "${cmds[@]}"; do
      echo "codeq all: $c" >&2
      printf '\n## %s\n\n```\n' "$c"
      if ! ("cmd_$c" 2>&1); then
        echo "codeq $c FAILED"
        failed+=("$c")
      fi
      echo '```'
    done
    [ "${#failed[@]}" -eq 0 ] || printf '\nFailed: %s\n' "${failed[*]}"
  } >"$OUT/REPORT.md"
  echo "report: $OUT/REPORT.md"
  [ "${#failed[@]}" -eq 0 ] || die "failed: ${failed[*]} (details in the report)"
}

while [ $# -gt 0 ]; do
  case "$1" in
  -o)
    OUT="$(realpath -m "$2")"
    shift 2
    ;;
  --tests)
    INCLUDE_TESTS=1
    shift
    ;;
  *) break ;;
  esac
done

cmd="${1:-help}"
[ $# -gt 0 ] && shift
case "$cmd" in
help | -h | --help) usage ;;
loc | complexity | dup | cycles | overview | coupling | design | bugs | coverage | all) "cmd_$cmd" "$@" ;;
*)
  usage >&2
  die "unknown command: $cmd"
  ;;
esac
