name = "Main 1.21.11"
author = "addg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "327b480c8e5015b631a33a6c36e3437245c2abdac7f65e0b5988d00c05a3a399"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
