name = "Main 1.21.11"
author = "addg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c88eeed18205bf59fad42b0faeaa071f33598ad0fdb022a3c83e76a8b2059b1"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
