name = "Main 1.21.11"
author = "addg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "113c32b6b0825ba76f8d8646a7575b494cd8782cb1709ee0cdca7333ab1aff67"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
