keys:
  # Administrative keys - full access to all secrets
  admins:
    - &admin_primary projects/prod-7f3c/locations/global/keyRings/sops-keyring/cryptoKeys/admin-primary

creation_rules:
  # Single rule for all secrets using admin primary key
  - key_groups:
      - gcp_kms:
        - resource_id: *admin_primary
