name: Build Nix Flakes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      # Configure Git to use HTTPS with GitHub token for private repositories
      # This is secure because:
      # - GITHUB_TOKEN is temporary and only valid for this workflow run
      # - Token has limited scope (read-only by default)
      # - HTTPS ensures encrypted communication
      # - Configuration is only applied to GitHub URLs
      - name: Configure Git for private repositories
        run: |
          git config --global url."https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/addg0/".insteadOf "git@github.com:addg0/"

      - name: Build flake
        run: |
          nix flake check
          nix build .#
